jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: install
      id: install
      run : pip install -r lint_requirements.txt

    - name: check
      id: flake8
      run: |
        flake8 --version
        flake8 src/yt_napari
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: install
      id: install
      run : pip install -r lint_requirements.txt
    - name: check
      id: black
      run: |
        black --version
        black --check --diff src/yt_napari/
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: install
      id: install
      run : pip install -r lint_requirements.txt
    - name: check
      id: isort
      run: |
        isort --version-number
        isort src/yt_napari --check --diff

  napari-plugin-check:
    name: napari-plugin-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: install
        id: install
        run: pip install git+https://github.com/tlambert03/napari-plugin-checks
      - name: check
        id: napari-plugin-check
        run: |
          napari-plugin-check .
